# Generated by Django 2.1.4 on 2018-12-07 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='La cedula debe contener exactamente 11 digitos', regex='^[0-9]{11}$')])),
                ('date_of_birth', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Debe ser un numero dominicano de 10 digitos', regex='^(809|829|849)[0-9]{7}$')])),
                ('gender', models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BankUser',
        ),
    ]
