# Generated by Django 2.1.4 on 2018-12-09 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181209_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Hombre'), (1, 'Mujer')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='La cedula debe contener exactamente 11 digitos', regex='^[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Debe ser un numero dominicano de 10 digitos', regex='^(809|829|849)[0-9]{7}$')]),
        ),
    ]
