# Generated by Django 2.1.4 on 2018-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181209_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(
                choices=[(0, 'Hombre'), (1, 'Mujer')], default=0),
        ),
    ]
