# Generated by Django 2.1.4 on 2018-12-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181209_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
