# Generated by Django 2.1.4 on 2018-12-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_loginlog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='locale',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
