# Generated by Django 2.1.4 on 2018-12-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_loginlog_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
