# Generated by Django 2.0.9 on 2019-01-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='core_id',
        ),
    ]
