# Generated by Django 2.1.4 on 2019-01-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190104_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityquestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='securityquestion',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
